export const fakeTweets = [
  {
    id: 1,
    name: "Elon Musk",
    username: "elonmusk",
    content: "Mars, nous voilà ! 🚀",
    time: "2h",
    avatar: "https://randomuser.me/api/portraits/men/1.jpg",
    media: "https://media.giphy.com/media/3o7aD2saalBwwftBIY/giphy.gif",
    mediaType: "gif",
    liked: false,
  },
  {
    id: 2,
    name: "NASA",
    username: "nasa",
    content: "Voici une nouvelle image incroyable de la galaxie ! 🌌✨",
    time: "5h",
    avatar: "https://randomuser.me/api/portraits/women/2.jpg",
    media:
      "https://cdn.spacetelescope.org/archives/images/screen/heic2007a.jpg",
    mediaType: "image",
    liked: false,
  },
  {
    id: 3,
    name: "React.js",
    username: "reactjs",
    content: "Les hooks changent la donne ! 🔥",
    time: "8h",
    avatar: "https://reactjs.org/logo-og.png",
  },
  {
    id: 4,
    name: "YouTube",
    username: "youtube",
    content: "Découvrez notre dernière vidéo sur l'IA 👀",
    time: "1j",
    avatar: "https://randomuser.me/api/portraits/men/3.jpg",
    media: "https://www.w3schools.com/html/mov_bbb.mp4",
    mediaType: "video",
    liked: false,
  },
  {
    id: 5,
    name: "Cristiano Ronaldo",
    username: "cristiano",
    content: "Grand match aujourd'hui ! 💪⚽",
    time: "2j",
    avatar: "https://randomuser.me/api/portraits/men/4.jpg",
    media: "https://media.giphy.com/media/l0HlMII6aR3S1KFC0/giphy.gif",
    mediaType: "gif",
    liked: false,
  },
  {
    id: 6,
    name: "ChatGPT",
    username: "chatgpt",
    content: "Je peux coder en React plus vite que vous 😜",
    time: "3j",
    avatar: "https://randomuser.me/api/portraits/women/5.jpg",
  },
  {
    id: 7,
    name: "Netflix",
    username: "netflix",
    content: "Nouveau film ce soir ! 🍿🔥",
    time: "4j",
    avatar: "https://randomuser.me/api/portraits/men/6.jpg",
    media:
      "https://upload.wikimedia.org/wikipedia/commons/7/7a/Netflix_logo.svg",
    mediaType: "image",
    liked: false,
  },
  {
    id: 8,
    name: "The Rock",
    username: "therock",
    content: "Il est temps de soulever de la fonte 💪",
    time: "5j",
    avatar: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    id: 9,
    name: "Taylor Swift",
    username: "taylorswift",
    content: "Nouvelle chanson en ligne ! 🎶",
    time: "6j",
    avatar: "https://randomuser.me/api/portraits/women/8.jpg",
    media: "https://www.w3schools.com/html/movie.mp4",
    mediaType: "video",
    liked: false,
  },
];
